# Generated by Django 4.2.1 on 2023-06-08 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Домен rambler.ru запрещен",
                        regex="@rambler.ru",
                    )
                ],
            ),
        ),
    ]
